name: CI (baseline)

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  test:
    name: Install & Test (no cache)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest -q

  docker-build:
    name: Docker Build (no cache)
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        run: |
          docker build -t flask-cicd-starter -f docker/Dockerfile .
